name: Analyze Code

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y gcc-multilib make libc6-dev:i386 bear clang-tidy

    - name: Generate compile commands code
      run: bear -- make -C PhoenixMud/src

    - name: Run clang-tidy
      run: run-clang-tidy -p . -j4